name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install LilyPond
      run: brew install nwhetsell/lilypond/lilypond-unstable && brew link lilypond-unstable

    - name: Create PDF
      run: lilypond falling-trees.ly

    - name: Archive
      uses: actions/upload-artifact@main
      with:
        name: falling-trees
        path: falling-trees.pdf
        if-no-files-found: error
